"""Add cityCode and countryCode to Payment database

Revision ID: 6a021d816331
Revises: 
Create Date: 2023-11-10 09:54:45.590301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a021d816331'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cityCode', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('countryCode', sa.String(), nullable=False))
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.drop_column('countryCode')
        batch_op.drop_column('cityCode')

    # ### end Alembic commands ###
